### ISSUE TITLE
Network definitions referencing each other create a loop

### ISSUE THREAD

**Issue by rbott** [rbott/arculus-fire.io#4]
The following definition will get the parser stuck in an infinite loop:

```yaml
---
net-objects:
  - name: mycorp-sample-net1
    include: mycorp-sample-net2
    nets:
      - 192.0.2.0/24
  - name: mycorp-sample-net2
    include: mycorp-sample-net1
    nets:
      - 198.51.100.0/24
```

While this is definitely not an useful configuration it might happen by accident with a growing list of definitions and the parser should detect this and present and error accordingly.
